# Generated by Django 5.0.1 on 2024-01-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_image_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.BooleanField(default=False),
        ),
    ]
